=== Nandu2105/wtl/Assignment3/employee.dtd
<!ELEMENT employees (employee+)>
<!ELEMENT employee (name, position, department, hire_year, salary)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT hire_year (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== Nandu2105/wtl/Assignment3/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="employee.xsl"?>
<!DOCTYPE employees SYSTEM "employee.dtd">
<employees>
    <employee>
        <name>Namrata Daphale</name>
        <position>Software Engineer</position>
        <department>IT</department>
        <hire_year>2015</hire_year>
        <salary>75000</salary>
    </employee>
    <employee>
        <name>Shamal Gaykwad</name>
        <position>Project Manager</position>
        <department>Management</department>
        <hire_year>2012</hire_year>
        <salary>90000</salary>
    </employee>
    <employee>
        <name>Jyoti Patil</name>
        <position>Data Analyst</position>
        <department>Analytics</department>
        <hire_year>2018</hire_year>
        <salary>68000</salary>
    </employee>
    <employee>
        <name>Vishval Fadatare</name>
        <position>Data Analyst</position>
        <department>Analytics</department>
        <hire_year>2018</hire_year>
        <salary>68000</salary>
    </employee>
</employees>
